version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgres

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

#version: '3'
#services:
#  web:
#    build: .
#    #volumes:
#    #  - "./docs:/src"
#    ports:
#      - "127.0.0.1:8080:8080"
#  db:
#    image: postgres
#    environment:
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_DB: ${DB_NAME}
#    ports:
#        - "127.0.0.1:5432:5432"
#
