# 2 service: golang api and redis
version: '3.7'
services:
  api:
    build: .
    container_name: api
    ports:
      - 127.0.0.1:3080:${SERVER_PORT}
    restart: always
    networks:
        - local
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - VIRTUAL_PORT=${SERVER_PORT}
  redis:
    image: redis
    container_name: redis
    networks:
      - local
    ports:
      - "127.0.0.1:6379:6379"
networks:
  local:
    driver: bridge