version: '3'
services:
  web:
    build: .
    #volumes:
    #  - "./docs:/src"
    ports:
      - "127.0.0.1:8080:8080"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
        - "127.0.0.1:5432:5432"

