version: '3'

services:
  hugo:
    image: klakegg/hugo:0.101.0-ext-alpine
    container_name: hugojgrpctask1
    command: server
    entrypoint: hugo
    volumes:
      - "./hugo:/src"
    ports:
      - "1313:1313"
    networks:
      - mylocal
  app:
    build: ./proxy
    container_name: proxyjgrpctask1
    volumes:
      - "./hugo/content:/app/static"
    ports:
      - "8080:8080"
    env_file:
      - ./proxy/.env
    networks:
      - mylocal
  jgrpc:
    build: ./jgrpc
    container_name: jgrpctask1
    ports:
      - "44972:44972"
    env_file:
      - ./proxy/.env
    networks:
      - mylocal
networks:
  mylocal:
    driver: bridge