// Code generated by mockery v2.35.4. DO NOT EDIT.

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockGithuber is an autogenerated mock type for the Githuber type
type MockGithuber struct {
	mock.Mock
}

// GetGists provides a mock function with given fields: ctx, username
func (_m *MockGithuber) GetGists(ctx context.Context, username string) ([]Item, error) {
	ret := _m.Called(ctx, username)

	var r0 []Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]Item, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []Item); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRepos provides a mock function with given fields: ctx, username
func (_m *MockGithuber) GetRepos(ctx context.Context, username string) ([]Item, error) {
	ret := _m.Called(ctx, username)

	var r0 []Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]Item, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []Item); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockGithuber creates a new instance of MockGithuber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGithuber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGithuber {
	mock := &MockGithuber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
