// Code generated by mockery v2.35.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Weather is an autogenerated mock type for the Weather type
type Weather struct {
	mock.Mock
}

// getWeather provides a mock function with given fields: city
func (_m *Weather) getWeather(city string) int {
	ret := _m.Called(city)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(city)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// NewWeather creates a new instance of Weather. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeather(t interface {
	mock.TestingT
	Cleanup(func())
}) *Weather {
	mock := &Weather{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
